services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  liff:
    build:
      context: .
      dockerfile: apps/liff/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./apps/liff/.env
