import './globals.css';
import '@sommhai/ui/styles.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { StrictMode } from 'react';

import AppLayout from '@/components/common/layout';
import { LiffProvider } from '@/contexts/global/liff';
import { QueryProvider } from '@/contexts/global/query';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StrictMode>
          <QueryProvider>
            <LiffProvider>
              <AppLayout>{children}</AppLayout>
            </LiffProvider>
          </QueryProvider>
        </StrictMode>
      </body>
    </html>
  );
}
