import './globals.css';
import '@sommhai/ui/styles.css';
import 'leaflet/dist/leaflet.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { StrictMode } from 'react';

import AppLayout from '@/components/common/layout';
import { LiffProvider } from '@/contexts/global/liff';
import { QueryProvider } from '@/contexts/global/query';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} antialiased`}>
        <StrictMode>
          <QueryProvider>
            <LiffProvider>
              <AppLayout>{children}</AppLayout>
            </LiffProvider>
          </QueryProvider>
        </StrictMode>
      </body>
    </html>
  );
}
