services:
  api:
    container_name: sommhai-api-dev
    image: ghcr.io/ice-106/sommhai-api:dev
    restart: always
    environment:
      - PORT=80
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.stripprefix-api.stripprefix.prefixes=/api
      - traefik.http.routers.sommhai-dev-api.rule=Host(`api.sommhai-dev.p-def.xyz`) || (Host(`sommhai-dev.p-def.xyz`) && PathPrefix(`/api`))
      - traefik.http.routers.sommhai-dev-api.middlewares=stripprefix-api@docker
      - traefik.http.routers.sommhai-dev-api.tls=true
      - traefik.http.routers.sommhai-dev-api.tls.certresolver=letsencrypt
      - traefik.http.services.sommhai-dev-api.loadbalancer.server.port=5001
    networks:
      - sommhai-network

networks:
  sommhai-network:
    name: sommhai-network
    external: true
