services:
  web:
    container_name: sommhai-liff-dev
    image: ghcr.io/ice-106/sommhai-liff:dev
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.sommhai-liff-dev.rule=Host(`sommhai-dev.p-def.xyz`)
      - traefik.http.routers.sommhai-liff-dev.tls=true
      - traefik.http.routers.sommhai-liff-dev.tls.certresolver=letsencrypt
      - traefik.http.services.sommhai-liff-dev.loadbalancer.server.port=80
    networks:
      - sommhai-network

networks:
  sommhai-network:
    name: sommhai-network
    external: true
