services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    env_file:
      - ./traefik/.env
    networks:
      - sommhai-dev-network
  preview-default:
    image: ghcr.io/tithanayut/hmci-default:latest
    container_name: preview-default
    restart: always
    networks:
      - sommhai-dev-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.preview-default.rule=HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.sommhai-dev.p-def.xyz`)
      - traefik.http.routers.preview-default.priority=1
      - traefik.http.routers.preview-default.tls=true
      - traefik.http.routers.preview-default.tls.certresolver=letsencrypt
      - traefik.http.routers.preview-default.tls.domains[0].main=sommhai-dev.p-def.xyz
      - traefik.http.routers.preview-default.tls.domains[0].sans=*.sommhai-dev.p-def.xyz

networks:
  sommhai-dev-network:
    driver: bridge
    external: true
