services:
  api:
    container_name: sommhai-api-dev
    image: ghcr.io/ice-106/sommhai-api:dev
    restart: always
    environment:
      - PORT=5001
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.stripprefix-api.stripprefix.prefixes=/api
      - traefik.http.routers.sommhai-api-dev.rule=Host(`api.sommhai-dev.p-def.xyz`) || (Host(`sommhai-dev.p-def.xyz`) && PathPrefix(`/api`))
      - traefik.http.routers.sommhai-api-dev.middlewares=stripprefix-api@docker
      - traefik.http.routers.sommhai-api-dev.tls=true
      - traefik.http.routers.sommhai-api-dev.tls.certresolver=letsencrypt
      - traefik.http.services.sommhai-api-dev.loadbalancer.server.port=5001
    networks:
      - sommhai-dev-network

networks:
  sommhai-dev-network:
    name: sommhai-dev-network
    external: true
